using System.Collections;
using Common.Data;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace Common.MonoBehaviours.MindPalace
{
    public class DraggableFragment : MonoBehaviour
    {
        [Header("Wrappers")]
        [SerializeField] private MonoBehaviourWrapper mousedOverSlot;
        [SerializeField] private MonoBehaviourWrapper mousedOverFragment;

        [Header("Input Action Asset")]
        [SerializeField] private InputActionAsset inputActions;
        private InputAction _pointAction;
        private InputAction _clickAction;
        // Autogenerated strings from Unity's Input Action Assets system
        private const string PointActionName = "UI/Point";
        private const string ClickActionName = "UI/Click";

        [Header("Fragment Animation")]
        [SerializeField] private float snapSpeedTime;
        private Vector2 _currentSnapPosition;
        private bool _isAnimating;
        private bool _isBeingDragged;
        
        [Header("Fragment Components")]
        [SerializeField] private Image glowImage;
        private RectTransform _rectTransform;

        private void Awake()
        {
            Debug.Assert(mousedOverSlot != null, nameof(mousedOverSlot) + " != null");
            Debug.Assert(mousedOverFragment != null, nameof(mousedOverFragment) + " != null");
            Debug.Assert(inputActions != null, nameof(inputActions) + " != null");
            Debug.Assert(glowImage != null, nameof(glowImage) + " != null");

            _rectTransform = GetComponent<RectTransform>();
            
            _pointAction = inputActions[PointActionName];
            _clickAction = inputActions[ClickActionName];

            mousedOverFragment.ReferenceChanged += SetGlow;
            _clickAction.started += ClickStarted;
        }

        private void OnDestroy()
        {
            mousedOverFragment.ReferenceChanged -= SetGlow;
            _clickAction.started -= ClickStarted;
        }

        private void Update()
        {
            if (_isBeingDragged) UpdateDrag();
        }

        private void MoveToPosition()
        {
            StopAllCoroutines();
            _isAnimating = false;

            StartCoroutine(AnimateToPosition());
        }
        
        private void MoveToPosition(Vector2 newPosition)
        {
            _currentSnapPosition = newPosition;
            
            MoveToPosition();
        }

        private IEnumerator AnimateToPosition()
        {
            _isAnimating = true;

            var initialPosition = _rectTransform.anchoredPosition;
            var timePassed = 0f;

            while (_rectTransform.anchoredPosition != _currentSnapPosition)
            {
                _rectTransform.anchoredPosition = Vector2.Lerp(
                    initialPosition,
                    _currentSnapPosition,
                    timePassed / snapSpeedTime
                );
                
                timePassed += Time.deltaTime;
                yield return null;
            }

            _isAnimating = false;
        }

        public void DestroyFragment()
        {
            Destroy(gameObject);
        }

        private void ClickStarted(InputAction.CallbackContext ctx)
        {
            if (mousedOverFragment.Current == this)
            {
                StartDrag();
                SetGlow();
            }
        }
        
        public void StartDrag()
        {
            if (_isAnimating) return;

            _clickAction.canceled += EndDrag;

            _isBeingDragged = true;
        }

        private void UpdateDrag()
        {
            var mousePosition = _pointAction.ReadValue<Vector2>();
    
            RectTransformUtility.ScreenPointToLocalPointInRectangle(
                transform.parent as RectTransform,
                mousePosition,
                null, // null is used when canvas is set to screen space overlay
                out var localPosition);

            _rectTransform.anchoredPosition = localPosition;
        }

        private void EndDrag(InputAction.CallbackContext ctx)
        {
            _clickAction.canceled -= EndDrag;

            if (!_isBeingDragged) return;
            _isBeingDragged = false;

            var slot = mousedOverSlot.Current;
            if (slot is not null) { MoveToPosition(slot.GetComponent<RectTransform>().anchoredPosition); }
            else MoveToPosition();
            
            mousedOverSlot.Set(null);
        }
        
        private void SetGlow()
        {
            glowImage.enabled = mousedOverFragment.Current == this && !_isBeingDragged;
        }
    }
}