using System.Collections;
using Common.Data;
using Common.Data.Fragments;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace Common.MonoBehaviours.MindPalace
{
    [RequireComponent(typeof(RectTransform))]
    public class DraggableFragment : MonoBehaviour
    {
        [Header("Wrappers")]
        [SerializeField] private MonoBehaviourWrapper mousedOverFragment;

        [Header("Input Action Asset")]
        [SerializeField] private InputActionAsset inputActions;
        private InputAction _pointAction;
        private InputAction _clickAction;
        // Autogenerated strings from Unity's Input Action Assets system
        private const string PointActionName = "UI/Point";
        private const string ClickActionName = "UI/Click";

        [Header("Fragment Animation")]
        [SerializeField] private float snapSpeedTime;
        private Vector3 _currentSnapPosition;
        private bool _isAnimating;
        private bool _isBeingDragged;
        private RectTransform _rectTransform;

        [Header("Fragment Components")]
        [SerializeField] private Image fragmentImage;
        [SerializeField] private Image glowImage;

        [Header("Stored Fragment Data")]
        [field: SerializeField] public FragmentData Data { get; private set; }

        private void Awake()
        {
            //Debug.Assert(mousedOverSlot != null, nameof(mousedOverSlot) + " != null");
            Debug.Assert(mousedOverFragment != null, nameof(mousedOverFragment) + " != null");
            Debug.Assert(inputActions != null, nameof(inputActions) + " != null");
            Debug.Assert(fragmentImage != null, nameof(fragmentImage) + " != null");
            Debug.Assert(glowImage != null, nameof(glowImage) + " != null");

            _rectTransform = GetComponent<RectTransform>();

            _pointAction = inputActions[PointActionName];
            _clickAction = inputActions[ClickActionName];

            mousedOverFragment.ReferenceChanged += SetGlow;
            _clickAction.started += ClickStarted;
            _clickAction.canceled += SetGlow;
        }

        public void InitializeFragment(FragmentData newFragmentData)
        {
            Data = newFragmentData;
            fragmentImage.color = Data.color;
        }

        private void OnDestroy()
        {
            mousedOverFragment.ReferenceChanged -= SetGlow;
            _clickAction.started -= ClickStarted;
            _clickAction.canceled -= SetGlow;
        }

        private void Update()
        {
            if (_isBeingDragged) UpdateDrag();
        }

        private void MoveToPosition()
        {
            StopAllCoroutines();
            _isAnimating = false;

            StartCoroutine(AnimateToPosition());
        }

        public void MoveToPosition(Vector3 newPosition)
        {
            _currentSnapPosition = newPosition;

            MoveToPosition();
        }

        private IEnumerator AnimateToPosition()
        {
            _isAnimating = true;

            var initialPosition = _rectTransform.position;
            var timePassed = 0f;

            while (_rectTransform.position != _currentSnapPosition)
            {
                _rectTransform.position = Vector3.Lerp(
                    initialPosition,
                    _currentSnapPosition,
                    timePassed / snapSpeedTime
                );

                timePassed += Time.deltaTime;
                yield return null;
            }

            _isAnimating = false;
        }

        public void DestroyFragment()
        {
            Destroy(gameObject);
        }

        private void ClickStarted(InputAction.CallbackContext ctx)
        {
            if (mousedOverFragment.Current == this)
            {
                StartDrag();
                SetGlow();
            }
        }

        private void StartDrag()
        {
            if (_isAnimating) return;

            _clickAction.canceled += ClickCanceled;

            _isBeingDragged = true;
            transform.SetAsLastSibling(); // this makes it so it doesn't disappear behind other fragments.
        }

        private void UpdateDrag()
        {
            var mousePosition = _pointAction.ReadValue<Vector2>();

            RectTransformUtility.ScreenPointToLocalPointInRectangle(
                transform.parent as RectTransform,
                mousePosition,
                null, // null is used when canvas is set to screen space overlay
                out var localPosition);

            _rectTransform.anchoredPosition = localPosition;
        }

        private void ClickCanceled(InputAction.CallbackContext ctx)
        {
            _clickAction.canceled -= ClickCanceled;

            if (!_isBeingDragged) return;
            _isBeingDragged = false;
            
            if (!_isAnimating) MoveToPosition();
        }

        private void SetGlow()
        {
            glowImage.enabled = !_clickAction.IsInProgress() && mousedOverFragment.Current == this;
        }
        
        private void SetGlow(InputAction.CallbackContext ctx) => SetGlow();
    }
}