using System;
using Common.Data;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace Common.MonoBehaviours.MindPalace
{
    public class FragmentDropSlot : MonoBehaviour
    {
        [Header("Wrappers")]
        [SerializeField] private MonoBehaviourWrapper mousedOverSlot;
        [SerializeField] private MonoBehaviourWrapper mousedOverFragment;

        [Header("Components")]
        [SerializeField] private Image glowImage;

        [Header("Input Action Asset")]
        [SerializeField] private InputActionAsset inputActions;
        private InputAction _clickAction;
        // Autogenerated strings from Unity's Input Action Assets system
        private const string ClickActionName = "UI/Click";

        [Header("Slot State")]
        [field: SerializeField] public DraggableFragment OccupiedFragment { get; private set; }
        public bool IsOccupied => OccupiedFragment != null;

        public event Action OccupancyChanged;

        private void Awake()
        {
            Debug.Assert(mousedOverSlot != null, nameof(mousedOverSlot) + " != null");
            Debug.Assert(mousedOverFragment != null, nameof(mousedOverFragment) + " != null");
            Debug.Assert(glowImage != null, nameof(glowImage) + " != null");

            _clickAction = inputActions[ClickActionName];

            mousedOverSlot.ReferenceChanged += SetGlow;
            _clickAction.started += SetGlow;
            _clickAction.canceled += SetGlow;
        }

        private void OnDestroy()
        {
            mousedOverSlot.ReferenceChanged -= SetGlow;
        }

        public void RegisterFragment(DraggableFragment fragment)
        {
            OccupiedFragment = fragment;
            OccupancyChanged?.Invoke();
            SetGlow();
        }

        public void UnregisterFragment()
        {
            OccupiedFragment = null;
            SetGlow();
        }

        private void SetGlow()
        {
            glowImage.enabled = _clickAction.IsInProgress() && mousedOverSlot.Current == this;
        }

        private void SetGlow(InputAction.CallbackContext ctx) => SetGlow();
    }
}