using System;
using Common.Data;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace Common.MonoBehaviours.MindPalace
{
    [RequireComponent(typeof(RectTransform))]
    public class FragmentDropSlot : MonoBehaviour
    {
        [Header("Wrappers")]
        [SerializeField] private MonoBehaviourWrapper mousedOverSlot;
        [SerializeField] private MonoBehaviourWrapper mousedOverFragment;

        [Header("Components")]
        [SerializeField] private Image glowImage;
        private RectTransform _rectTransform;

        [Header("Input Action Asset")]
        [SerializeField] private InputActionAsset inputActions;
        private InputAction _clickAction;
        // Autogenerated strings from Unity's Input Action Assets system
        private const string ClickActionName = "UI/Click";

        [Header("Slot State")]
        [field: SerializeField] public DraggableFragment OccupiedFragment { get; private set; }
        public bool IsOccupied => OccupiedFragment != null;
        private bool _draggingFragment;

        public event Action OccupancyChanged;

        private void Awake()
        {
            Debug.Assert(mousedOverSlot != null, nameof(mousedOverSlot) + " != null");
            Debug.Assert(mousedOverFragment != null, nameof(mousedOverFragment) + " != null");
            Debug.Assert(glowImage != null, nameof(glowImage) + " != null");
            
            _clickAction = inputActions[ClickActionName];

            mousedOverSlot.ReferenceChanged += SetGlow;
            _clickAction.started += ClickStarted;
            _clickAction.canceled += ClickCanceled;
            
            _rectTransform = gameObject.GetComponent<RectTransform>();
        }

        private void OnDestroy()
        {
            mousedOverSlot.ReferenceChanged -= SetGlow;
            _clickAction.started -= ClickStarted;
            _clickAction.canceled -= ClickCanceled;
        }

        public void RegisterFragment(DraggableFragment fragment)
        {
            OccupiedFragment = fragment;
            fragment.MoveToPosition(_rectTransform.position);
            OccupancyChanged?.Invoke();
        }

        public void UnregisterFragment()
        {
            OccupiedFragment = null;
        }

        private void ClickStarted(InputAction.CallbackContext ctx)
        {
            if (mousedOverFragment.Current != null) _draggingFragment = true;
            SetGlow();
        }

        private void ClickCanceled(InputAction.CallbackContext ctx)
        {
            SetGlow();

            var mousedSlot = mousedOverSlot.Current as FragmentDropSlot;
            var mousedFragment = mousedOverFragment.Current as DraggableFragment;

            if (mousedSlot == null || mousedFragment == null) return;

            if (mousedSlot == this && !IsOccupied)
            {
                RegisterFragment(mousedFragment);
            }
            else if (mousedSlot != this &&
                     (!mousedSlot.IsOccupied || mousedSlot.OccupiedFragment == mousedFragment) &&
                     OccupiedFragment == mousedFragment)
            {
                UnregisterFragment();
            }
        }
        
        private void SetGlow()
        {
            glowImage.enabled = _draggingFragment && _clickAction.IsInProgress() && mousedOverSlot.Current == this;
        }
    }
}