using System.Collections.Generic;
using Common.Data;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;

namespace Common.MonoBehaviours.MindPalace
{
    public class PalaceMouseController : MonoBehaviour
    {
        [Header("Wrappers")]
        [SerializeField] private BoolWrapper isMindPalaceActive;
        [SerializeField] private MonoBehaviourWrapper mousedOverFragment;
        [SerializeField] private MonoBehaviourWrapper mousedOverSlot;
        
        [Header("Input Action Asset")]
        [SerializeField] private InputActionAsset inputActions;
        private InputAction _pointAction;
        // Autogenerated strings from Unity's Input Action Assets system
        private const string PointActionName = "UI/Point";
        
        private void Awake()
        {
            Debug.Assert(isMindPalaceActive != null, nameof(isMindPalaceActive) + " != null");
            Debug.Assert(inputActions != null, nameof(inputActions) + " != null");
            
            inputActions.Enable();
            
            _pointAction = inputActions[PointActionName];
        }

        private void Update()
        {
            if (isMindPalaceActive) UpdateHover();
        }

        private void UpdateHover()
        {
            var mousePos = _pointAction.ReadValue<Vector2>();
            
            var hitFragmentResults = UIRaycast<DraggableFragment>(mousePos);
            mousedOverFragment.Set(hitFragmentResults);
            
            var hitSlotResults = UIRaycast<FragmentDropSlot>(mousePos);
            mousedOverSlot.Set(hitSlotResults);
        }
        
        private static T UIRaycast<T>(Vector2 screenPos) where T : MonoBehaviour
        {
            var results = new List<RaycastResult>();
            var pointerData = new PointerEventData(EventSystem.current) { position = screenPos };
            EventSystem.current.RaycastAll(pointerData, results); // Grabbing all objects hit under the pointer
            
            foreach (var result in results)
            {
                if (result.gameObject.TryGetComponent<T>(out var component))
                {
                    return component;
                }
            }
            
            return null;
        }
    }
}